<?php
$message .='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';
$message .='<html xmlns="http://www.w3.org/1999/xhtml">';
$message .='<head>';
$message .='<meta http-equiv="Content-Type" content="text/html; charset=utf-8">';
$message .='<meta name="viewport" content="width=device-width">';
$message .='<meta name="title" content="School">';
$message .='<style>';
$message .='a:hover{color:#147dc2}';
$message .='a:active{color:#147dc2}';
$message .='h1 a:visited{color:#483729}';
$message .='h2 a:visited{color:#483729}';
$message .='h3 a:visited{color:#483729}';
$message .='h4 a:visited{color:#483729}';
$message .='h5 a:visited{color:#483729}';
$message .='h6 a:visited{color:#483729}';
$message .='table.button:hover table tr td a{color:#000000}';
$message .='table.button:active table tr td a{color:#000000}';
$message .='table.button table tr td a:visited{color:#000000}';
$message .='table.button.tiny:hover table tr td a{color:#000000}';
$message .='table.button.tiny:active table tr td a{color:#000000}';
$message .='table.button.tiny table tr td a:visited{color:#000000}';
$message .='table.button.small:hover table tr td a{color:#000000}';
$message .='table.button.small:active table tr td a{color:#000000}';
$message .='table.button.small table tr td a:visited{color:#000000}';
$message .='table.button.large:hover table tr td a{color:#000000}';
$message .='table.button.large:active table tr td a{color:#000000}';
$message .='table.button.large table tr td a:visited{color:#000000}';
$message .='table.button.secondary:hover table td{background:#919191;color:#fefefe}';
$message .='table.button.secondary:hover table a{border:0 solid #919191}';
$message .='table.button.secondary:hover table td a{color:#fefefe}';
$message .='table.button.secondary:active table td a{color:#fefefe}';
$message .='table.button.secondary table td a:visited{color:#fefefe}';
$message .='table.button.success:hover table td{background:#23bf5d}';
$message .='table.button.success:hover table a{border:0 solid #23bf5d}';
$message .='table.button.alert:hover table td{background:#e23317}';
$message .='table.button.alert:hover table a{border:0 solid #e23317}';
$message .='.thumbnail:hover{box-shadow:0 0 6px 1px rgba(33, 153, 232, 0.5)}';
$message .='.thumbnail:focus{box-shadow:0 0 6px 1px rgba(33, 153, 232, 0.5)}';
$message .='.text-orange-link:hover{color:#f9b32e}';
$message .='.button-orange:hover{background-color:#f9b32e}';
$message .='table.button-orange:hover table tr td a{color:#ffffff}';
$message .='table.button-orange:active table tr td a{color:#ffffff}';
$message .='table.button-orange table tr td a:visited{color:#ffffff}';
$message .='table.button-orange.tiny:hover table tr td a{color:#ffffff}';
$message .='table.button-orange.tiny:active table tr td a{color:#ffffff}';
$message .='table.button-orange.tiny table tr td a:visited{color:#ffffff}';
$message .='table.button-orange.small:hover table tr td a{color:#ffffff}';
$message .='table.button-orange.small:active table tr td a{color:#ffffff}';
$message .='table.button-orange.small table tr td a:visited{color:#ffffff}';
$message .='table.button-orange.large:hover table tr td a{color:#ffffff}';
$message .='table.button-orange.large:active table tr td a{color:#ffffff}';
$message .='table.button-orange.large table tr td a:visited{color:#ffffff}';
$message .='table.button-orange:hover table td{background:#f9b32e;color:#fefefe}';
$message .='table.button-orange:visited table td{background:#f9b32e;color:#fefefe}';
$message .='table.button-orange:active table td{background:#f9b32e;color:#fefefe}';
$message .='table.button-orange:hover table a{border:0 solid #f9b32e}';
$message .='table.button-orange:visited table a{border:0 solid #f9b32e}';
$message .='table.button-orange:active table a{border:0 solid #f9b32e}';
$message .='.text-green-link:hover{color:rgb(103, 79, 59)}';
$message .='a:hover{color:rgb(103, 79, 59)}';
$message .='table.button-green:hover table tr td a{color:#ffffff}';
$message .='table.button-green:active table tr td a{color:#ffffff}';
$message .='table.button-green table tr td a:visited{color:#ffffff}';
$message .='table.button-green.tiny:hover table tr td a{color:#ffffff}';
$message .='table.button-green.tiny:active table tr td a{color:#ffffff}';
$message .='table.button-green.tiny table tr td a:visited{color:#ffffff}';
$message .='table.button-green.small:hover table tr td a{color:#ffffff}';
$message .='table.button-green.small:active table tr td a{color:#ffffff}';
$message .='table.button-green.small table tr td a:visited{color:#ffffff}';
$message .='table.button-green.large:hover table tr td a{color:#ffffff}';
$message .='table.button-green.large:active table tr td a{color:#ffffff}';
$message .='table.button-green.large table tr td a:visited{color:#ffffff}';
$message .='table.button-green:hover table td{background:#9DD64F;color:#fefefe}';
$message .='table.button-green:visited table td{background:#9DD64F;color:#fefefe}';
$message .='table.button-green:active table td{background:#9DD64F;color:#fefefe}';
$message .='table.button-green:hover table a{border:0 solid #9DD64F}';
$message .='table.button-green:visited table a{border:0 solid #9DD64F}';
$message .='table.button-green:active table a{border:0 solid #9DD64F}';
$message .='.button.bg-yellow:hover{background-color:#ffdc99}';
$message .='.footer .menu th:not(:first-child):before{content:" | "}';
$message .='.before-triangle:before{content:"";width:0;height:0;border-top:9px solid transparent;border-left:12px solid #ffc14b;border-bottom:9px solid transparent;margin-left:-20px;margin-top:2px;position:absolute;clear:both}';
$message .='</style>';
$message .='<style type="text/css">';
$message .='.ExternalClass {';
$message .='width: 100%';
$message .='}';
$message .='.ExternalClass,';
$message .='.ExternalClass p,';
$message .='.ExternalClass span,';
$message .='.ExternalClass font,';
$message .='.ExternalClass td,';
$message .='.ExternalClass div {';
$message .='line-height: 100%';
$message .='}';
$message .='@media only screen {';
$message .='html {';
$message .='min-height: 100%;';
$message .='background: #f3f3f3';
$message .='}';
$message .='}';
$message .='/*Columns Padding*/';
$message .='@media only screen and (max-width: 596px) {';
$message .='.small-float-center {';
$message .='margin: 0 auto!important;';
$message .='float: none!important;';
$message .='text-align: center!important';
$message .='}';
$message .='.small-text-center {';
$message .='text-align: center!important';
$message .='}';
$message .='.small-text-left {';
$message .='text-align: left!important';
$message .='}';
$message .='.small-text-right {';
$message .='text-align: right!important';
$message .='}';
$message .='}';
$message .='@media only screen and (max-width: 596px) {';
$message .='table.body table.container .hide-for-large {';
$message .='display: block!important;';
$message .='width: auto!important;';
$message .='overflow: visible!important';
$message .='}';
$message .='}';
$message .='@media only screen and (max-width: 596px) {';
$message .='table.body table.container .row.hide-for-large,';
$message .='table.body table.container .row.hide-for-large {';
$message .='display: table!important;';
$message .='width: 100%!important';
$message .='}';
$message .='}';
$message .='@media only screen and (max-width: 596px) {';
$message .='table.body table.container .show-for-large {';
$message .='display: none!important;';
$message .='width: 0;';
$message .='mso-hide: all;';
$message .='overflow: hidden';
$message .='}';
$message .='}';
$message .='@media only screen and (max-width: 596px) {';
$message .='table.body img {';
$message .='width: auto!important;';
$message .='height: auto!important';
$message .='}';
$message .='table.body center {';
$message .='min-width: 0!important';
$message .='}';
$message .='table.body .container {';
$message .='width: 95%!important';
$message .='}';
$message .='table.body .columns,';
$message .='table.body .column {';
$message .='height: auto!important;';
$message .='-moz-box-sizing: border-box;';
$message .='-webkit-box-sizing: border-box;';
$message .='box-sizing: border-box;';
$message .='}';
$message .='table.body .columns .column,';
$message .='table.body .columns .columns,';
$message .='table.body .column .column,';
$message .='table.body .column .columns {';
$message .='padding-left: 6px!important;';
$message .='padding-right: 6px!important';
$message .='}';
$message .='table.body .collapse .columns,';
$message .='table.body .collapse .column {';
$message .='padding-left: 0!important;';
$message .='padding-right: 0!important';
$message .='}';
$message .='td.small-1,';
$message .='th.small-1 {';
$message .='display: inline-block!important;';
$message .='width: 8.33333%!important';
$message .='}';
$message .='td.small-2,';
$message .='th.small-2 {';
$message .='display: inline-block!important;';
$message .='width: 16.66667%!important';
$message .='}';
$message .='td.small-3,';
$message .='th.small-3 {';
$message .='display: inline-block!important;';
$message .='width: 25%!important';
$message .='}';
$message .='td.small-4,';
$message .='th.small-4 {';
$message .='display: inline-block!important;';
$message .='width: 33.33333%!important';
$message .='}';
$message .='td.small-5,';
$message .='th.small-5 {';
$message .='display: inline-block!important;';
$message .='width: 41.66667%!important';
$message .='}';
$message .='td.small-6,';
$message .='th.small-6 {';
$message .='display: inline-block!important;';
$message .='width: 50%!important';
$message .='}';
$message .='td.small-7,';
$message .='th.small-7 {';
$message .='display: inline-block!important;';
$message .='width: 58.33333%!important';
$message .='}';
$message .='td.small-8,';
$message .='th.small-8 {';
$message .='display: inline-block!important;';
$message .='width: 66.66667%!important';
$message .='}';
$message .='td.small-9,';
$message .='th.small-9 {';
$message .='display: inline-block!important;';
$message .='width: 75%!important';
$message .='}';
$message .='td.small-10,';
$message .='th.small-10 {';
$message .='display: inline-block!important;';
$message .='width: 83.33333%!important';
$message .='}';
$message .='td.small-11,';
$message .='th.small-11 {';
$message .='display: inline-block!important;';
$message .='width: 91.66667%!important';
$message .='}';
$message .='td.small-12,';
$message .='th.small-12 {';
$message .='display: inline-block!important;';
$message .='width: 100%!important';
$message .='}';
$message .='.columns td.small-12,';
$message .='.column td.small-12,';
$message .='.columns th.small-12,';
$message .='.column th.small-12 {';
$message .='display: block!important;';
$message .='width: 100%!important';
$message .='}';
$message .='table.body td.small-offset-1,';
$message .='table.body th.small-offset-1 {';
$message .='margin-left: 8.33333%!important';
$message .='}';
$message .='table.body td.small-offset-2,';
$message .='table.body th.small-offset-2 {';
$message .='margin-left: 16.66667%!important';
$message .='}';
$message .='table.body td.small-offset-3,';
$message .='table.body th.small-offset-3 {';
$message .='margin-left: 25%!important';
$message .='}';
$message .='table.body td.small-offset-4,';
$message .='table.body th.small-offset-4 {';
$message .='margin-left: 33.33333%!important';
$message .='}';
$message .='table.body td.small-offset-5,';
$message .='table.body th.small-offset-5 {';
$message .='margin-left: 41.66667%!important';
$message .='}';
$message .='table.body td.small-offset-6,';
$message .='table.body th.small-offset-6 {';
$message .='margin-left: 50%!important';
$message .='}';
$message .='table.body td.small-offset-7,';
$message .='table.body th.small-offset-7 {';
$message .='margin-left: 58.33333%!important';
$message .='}';
$message .='table.body td.small-offset-8,';
$message .='table.body th.small-offset-8 {';
$message .='margin-left: 66.66667%!important';
$message .='}';
$message .='table.body td.small-offset-9,';
$message .='table.body th.small-offset-9 {';
$message .='margin-left: 75%!important';
$message .='}';
$message .='table.body td.small-offset-10,';
$message .='table.body th.small-offset-10 {';
$message .='margin-left: 83.33333%!important';
$message .='}';
$message .='table.body td.small-offset-11,';
$message .='table.body th.small-offset-11 {';
$message .='margin-left: 91.66667%!important';
$message .='}';
$message .='table.body table.columns td.expander,';
$message .='table.body table.columns th.expander {';
$message .='display: none!important';
$message .='}';
$message .='table.body .right-text-pad,';
$message .='table.body .text-pad-right {';
$message .='padding-left: 10px!important';
$message .='}';
$message .='table.body .left-text-pad,';
$message .='table.body .text-pad-left {';
$message .='padding-right: 10px!important';
$message .='}';
$message .='table.menu {';
$message .='width: 100%!important';
$message .='}';
$message .='table.menu td,';
$message .='table.menu th {';
$message .='width: auto!important;';
$message .='display: inline-block!important';
$message .='}';
$message .='table.menu.vertical td,';
$message .='table.menu.vertical th,';
$message .='table.menu.small-vertical td,';
$message .='table.menu.small-vertical th {';
$message .='display: block!important';
$message .='}';
$message .='table.menu[align="center"] {';
$message .='width: auto!important';
$message .='}';
$message .='}';
$message .='/*Custom */';
$message .='/*Column Reset*/';
$message .='/*Blue*/';
$message .='/* gray */';
$message .='/* green*/';
$message .='/*dark green*/';
$message .='/*Orange*/';
$message .='/* light */';
$message .='/*Orange Button*/';
$message .='/*Orange Hover*/';
$message .='/*Green Button*/';
$message .='/*green Hover*/';
$message .='/*ADDITIONAL CSS FOR THIS PAGE*/';
$message .='@media only screen and (max-width: 596px) {';
$message .='.show-mobile {';
$message .='display: block !important;';
$message .='width: auto !important;';
$message .='max-height: inherit !important;';
$message .='overflow: visible !important;';
$message .='float: none !important;';
$message .='}';
$message .='.hide-mobile {';
$message .='display: none !important;';
$message .='}';
$message .='.mobile-word-wrap br {';
$message .='display: none;';
$message .='}';
$message .='}';
$message .='</style>';
$message .='</head>';
$message .='<body style="min-width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;width:100% !important;">';
$message .='<!-- <style> -->';
$message .='<table class="body" data-made-with-foundation="" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;background:#f3f3f3;height:100%;width:100%;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;background-color: #ffffff;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="float-center" align="center" valign="top" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;float:none;text-align:center;border-collapse:collapse !important;">';
$message .='<center data-parsed="" style="width:100%;min-width:580px;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="20px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:20px;line-height:20px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table border="0" cellspacing="0" cellpadding="0" class="wrapper float-center" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;margin:0 auto;float:none;text-align:center;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="container " border="0" cellspacing="0" cellpadding="0" width="600" align="center" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;background:#fefefe;width:600px;margin:0 auto;text-align:inherit;background-color: #f7f8f9;margin: 0 auto 0 auto; width: 600px;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="wrapper" align="center" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;background-color:#ffffff;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" height="" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="wrapper  header-with-image" align="center" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" height="" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<div>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns last px-0" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-right:6px;padding-right:0px !important;padding-left:0px !important;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;vertical-align:middle;text-align:center;">';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;background: #d49a8c;">';
$message .='<a href="http://www.firstvotenc.org/" title="Free Shipping!" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;">';
$message .='<img src="'.$home_url.'/wp-content/plugins/custom-send-mail/img/background.jpg" class="" title="First Vote NC" alt="First Vote NC" style="outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;width:auto;max-width:100%;clear:both;display:block;border:none;width:100%;font-size: 40px;line-height: 60px; text-align:center;color:#000000;min-height: 100px;background: #ffffff;     white-space: pre-line;"/>';
$message .='</a>';
$message .='</center>';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="20px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:20px;line-height:20px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<img src="'.$home_url.'/wp-content/plugins/custom-send-mail/img/star.png" class="text-center " title="⭐" alt="⭐" style="outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;width:auto;max-width:100%;clear:both;display:block;margin:0 auto;float:none;text-align:center;text-align:center !important;line-height:40px;width:auto;font-size: 42px;text-align:text-center;color:#151a47;"/>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="10px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:10px;line-height:10px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<h1 class="nc-blue-text text-center bold" style="color:inherit;word-wrap:normal;font-family:\'Times New Roman\', Times, serif;font-weight:400;margin:0;line-height:1.3;font-size:42px;color:#8DC63F;color:#151a47;font-weight:bold;text-align:center;text-align:center !important;">Welcome to First Vote!</h1>';
$message .='</center>';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="10px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:10px;line-height:10px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<img src="'.$home_url.'/wp-content/plugins/custom-send-mail/img/star.png" class="text-center " title="⭐" alt="⭐" style="outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;width:auto;max-width:100%;clear:both;display:block;margin:0 auto;float:none;text-align:center;text-align:center !important;line-height:40px;width:auto;font-size: 42px;text-align:text-center;color:#151a47;"/>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="10px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:10px;line-height:10px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="0px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:0px;line-height:0px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</div>';
$message .='</td>';
$message .='</tr>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</table>';
$message .='<table class="wrapper bg-white" align="" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;background-color:#ffffff;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="15px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:15px;line-height:15px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns   px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class=" px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='Thank you for signing up for First Vote NC: Local Elections 2017.';
$message .='</p>';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='It speaks well of your leadership and your willingness to explore new opportunities for your students.';
$message .='</p>';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='We have developed an engaging and impactful project-based resource that aligns with standards and provides ';
$message .='you with tools to energize your students to become civically connected.';
$message .='</p>';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='Check out the 17 lesson plans now available on our website, and look for 3 additional modules by Carolina K-12 ';
$message .='on local elections that will be available starting September 1st.';
$message .='</p>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="15px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:15px;line-height:15px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="wrapper nc-gray-bg" align="" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;background-color:#dcdfe5;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="35px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:35px;line-height:35px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns   px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class=" px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<h2 class="nc-blue-text text-center " style="color:inherit;word-wrap:normal;font-family:\'Times New Roman\', Times, serif;font-weight:400;margin:0;line-height:1.3;font-size:34px;color:#8DC63F;font-weight:bold;color:#151a47;text-align:center;text-align:center !important;">';
$message .='Important Information';
$message .='</h2>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="35px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:35px;line-height:35px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<p class="nc-red-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#861719;text-align:left;">';
$message .='We\'ve made you a custom url for your school, <a class="text-no-underline nc-red-text bold nc-blue-text" href="'.$schoolURL.'/" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#861719;color:#151a47;text-decoration:none;font-weight:bold;">'.$schoolName.'</a>!';
$message .='</p>';
$message .='<p class="nc-red-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#861719;text-align:left;">';
$message .='Your custom url is: <a class="text-no-underline nc-red-text bold nc-blue-text" href="'.$schoolURL.'/" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#861719;color:#151a47;text-decoration:none;font-weight:bold;">'.$schoolURL.'/</a>';
$message .='</p>';
$message .='<p class="nc-red-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#861719;text-align:left;">';
$message .='You can login in at: <a class="text-no-underline nc-red-text bold nc-blue-text" href="'.$home_url.'/teacher-login/" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#861719;color:#151a47;text-decoration:none;font-weight:bold;">'.$home_url.'/teacher-login/</a> for access ';
$message .='to your custom site.';
$message .='</p>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="wrapper nc-blue-bg" align="" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;background-color:#151a47;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="35px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:35px;line-height:35px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns   px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class=" px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<h2 class="text-white  text-center " style="color:inherit;word-wrap:normal;font-family:\'Times New Roman\', Times, serif;font-weight:400;margin:0;line-height:1.3;font-size:34px;color:#8DC63F;font-weight:bold;color:#ffffff;text-align:center;text-align:center !important;">';
$message .='Getting Started';
$message .='</h2>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="35px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:35px;line-height:35px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<p class="text-white text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#ffffff;text-align:left;">';
$message .='To get started with your account, Use this password <span class="bold nc-red-text" style="color:#861719 !important;font-weight: bold;">'.$plaintext_pass.'</span> or you can click the button below and reset your password.';
$message .='</p>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;position:relative;width:100%;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-3 columns first" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-bottom:6px;width:129px;padding-left:8px;padding-right:8px;padding-left:6px;width:25%;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="1px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:1px;line-height:1px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='<th class="small-12 large-6 columns " style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:274px;padding-left:8px;padding-right:8px;width:50%;">';
$message .='<table class=" button nc-red-bg large expand text-white text-center border-radius" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;background-color:#861719;color:#ffffff;text-align:center;margin:0 0 2px;border-radius:0px;width:100%;text-align:center !important;width:auto !important;width:100% !important;border-radius:10px !important;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="text-center" align="center" valign="middle" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;text-align:center;border-collapse:collapse !important;text-align:center !important;">';
$message .='<center style="width:100%;min-width:580px;min-width:242px;min-width:532px;min-width:0;min-width: auto;" data-parsed="">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="text-center text-white" align="center" valign="middle" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;color:#ffffff;text-align:center;text-align:left;border-collapse:collapse !important;text-align:center !important;">';
$message .='<center align="center" class="text-center" data-parsed="" style="width:100%;min-width:580px;min-width:242px;min-width:532px;min-width:0;text-align:center !important;min-width: auto;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="10px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;text-align:left;border-collapse:collapse !important;font-size:10px;line-height:10px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<a href="'.$home_url.'/lost-password/" class="text-center text-white min-h-20 " title="Get started!" style="color:#0a0a0a;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#ffffff;min-height:20px;font-family:Helvetica, Arial, sans-serif;font-size:16px;font-weight:300;text-decoration:none;display:inline-block;padding:8px 16px;border-radius:3px;padding:0px 20px;font-size:15px;text-align:center;width:100%;padding-left:0;padding-right:0;text-align:center !important;">';
$message .='<p class="text-white lead" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#ffffff;font-size:20px;line-height:1.6;"><span class="bold" style="font-weight:bold;">GET STARTED</span></p>';
$message .='</a>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="5px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;text-align:left;border-collapse:collapse !important;font-size:5px;line-height:5px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</center>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</center>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='<th class="small-12 large-3 columns last" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:129px;padding-left:8px;padding-right:8px;padding-right:6px;width:25%;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="1px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:1px;line-height:1px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="wrapper bg-white" align="" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;background-color:#ffffff;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="35px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:35px;line-height:35px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns   px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-left:6px;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class=" px-5" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;padding-right:30px !important;padding-left:30px !important;">';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<h2 class="nc-blue-text text-center " style="color:inherit;word-wrap:normal;font-family:\'Times New Roman\', Times, serif;font-weight:400;margin:0;line-height:1.3;font-size:34px;color:#8DC63F;font-weight:bold;color:#151a47;text-align:center;text-align:center !important;">';
$message .='Thank You!';
$message .='</h2>';
$message .='</center>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='In the meantime if you have questions, please don\'t hesitate to contact me. My email is ';
$message .='<a class="text-no-underline bold nc-blue-text" href="mailto:hunterbuxton@gmail.com" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#151a47;text-decoration:none;font-weight:bold;">hunterbuxton@gmail.com</a> and my cell number is ';
$message .='<a class="text-no-underline bold nc-blue-text" href="tel:919-605-5317" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#151a47;text-decoration:none;font-weight:bold;">919-605-5317</a>.';
$message .='</p>';
$message .='<p class="nc-blue-text text-left " style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;text-align:left;">';
$message .='We are grateful for your willingness to explore this opportunity. We understand the tremendous demands placed on teachers and our intent is to ';
$message .='not add to that burden, but provide a resource that brings excitement to this immensely important lesson.';
$message .='</p>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<p class="nc-blue-text text-left lh-15" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;line-height:15px;text-align:left;">';
$message .='Hunter Buxton';
$message .='</p>';
$message .='<p class="nc-blue-text text-left lh-15" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;line-height:15px;text-align:left;">';
$message .='Executive Director';
$message .='</p>';
$message .='<p class="nc-blue-text text-left lh-15" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#151a47;line-height:15px;text-align:left;">';
$message .='First Vote NC';
$message .='</p>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="25px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:25px;line-height:25px;">&nbsp;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="wrapper row  footer" align="center" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;background-color:#dcdfe5;padding:0;width:100%;position:relative;display:table;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td class="wrapper-inner" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;">';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="20px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:20px;line-height:20px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='<table class="row" style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;padding:0;width:100%;position:relative;display:table;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th class="small-12 large-12 columns first last" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin:0 auto;padding-bottom:6px;width:600px;padding-left:8px;padding-right:8px;padding-left:6px;padding-right:6px;">';
$message .='<table style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;width:100%;">';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<th style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;">';
$message .='<center style="width:100%;min-width:580px;min-width:532px;min-width: auto;">';
$message .='<p class="text-center nc-red-text text-center lh-15" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#861719;line-height:15px;text-align:center;text-align:center !important;">';
$message .='Have any questions?';
$message .='</p>';
$message .='<p class="text-center nc-red-text text-center" style="margin:0 0 0 10px;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;margin-bottom:10px;color:#84919D;color:#861719;text-align:center;text-align:center !important;">';
$message .='Email <a class="text-no-underline bold nc-blue-text" href="mailto:help@firstvote.com" style="color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;color:#8DC63F;text-decoration:underline;color:#151a47;text-decoration:none;font-weight:bold;">help@firstvote.com</a> for help';
$message .='</p>';
$message .='</center>';
$message .='</th>';
$message .='</tr>';
$message .='</table>';
$message .='</th>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</td>';
$message .='</tr>';
$message .='<table class="spacer" style="border-spacing:0;border-collapse:collapse;padding:0;vertical-align:top;text-align:left;">';
$message .='<tbody>';
$message .='<tr style="padding:0;vertical-align:top;text-align:left;">';
$message .='<td height="20px" style="word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;hyphens:auto;vertical-align:top;text-align:left;color:#0a0a0a;font-family:Helvetica, Arial, sans-serif;font-weight:400;padding:0;margin:0;line-height:1.3;font-size:18px;line-height:25px;border-collapse:collapse !important;font-size:20px;line-height:20px;">&#xA0;</td>';
$message .='</tr>';
$message .='</tbody>';
$message .='</table>';
$message .='</tbody>';
$message .='</table>';
$message .='</center>';
$message .='</td>';
$message .='</tr>';
$message .='</table>';
$message .='</body>';
$message .='</html>';

?>